site_name: 哔哩哔哩游戏SDK 接入文档
site_url: http://dev.biligame.com/
pages:
    - 游戏SDK接入文档: 
      - '哔哩哔哩游戏SDK集成指南': 'bili_b_android_sdk_doc.md'
      - '哔哩哔哩游戏服务端接口文档': 'bili_b_android_server.md'
      - '哔哩哔哩游戏SDK': 'bili_b_android_sdk.md'
      - '哔哩哔哩游戏接入FAQ': 'bili_b_android_sdk_faq.md'
    - 游戏数据SDK接入文档: 
      - '哔哩哔哩游戏数据SDK集成指南': 'bili_android_data_sdk_doc.md'
      - '哔哩哔哩游戏数据SDK': 'bili_android_data_sdk.md'
    - 工具: 
      - '自检工具': "bili_cp_check_doc.md"
theme: rtd-dropdown1